# Autor: Ana Luisa Castañeda Garce
#      W05 & W06 ADVENTURE GAME

import textwrap as tr
caps = "\033[91m {}\033[00m".format('CAPITALIZED')

print(f'\nWelcome adventurer!\n \nThis is your universe, you are the one that decides your fate.\n')
print(f'Remember to choose your options from the{caps} words :D \n')
ready = input(f'Are you ready for this adventure? (YES or NO) ')

if ready.lower() == 'no' :
    print("\nDon't worry, you can play other time. \n")
    print('')
    print("  _______ _    _ ______   ______ _   _ _____      ")
    print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
    print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
    print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
    print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
    print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
    print('')
elif ready.lower() == 'yes' :
    print(tr.fill("Your story starts as you overheard someone, mentioning that there is a treasure near your village. So, you decided that you'll find it yourself. "))
    print()
    print(tr.fill("The next day after arming yourself you embark on the bigest adventure of your life."))
    print()
    choice1 = input('Now, the question is do you go to the DESERT, the MOUNTAINS \nor the FOREST, all just outside your village. ')

    if choice1.lower() == 'desert' :
        print('')
        print("           ,,                               .-.")
        print("          || |                               ) )")
        print("          || |   ,                          '-'")
        print("          || |  | |")
        print("          || '--' |")
        print("    ,,    || .----'")
        print("   || |   || |")
        print("   |  '---'| |")
        print("   '------.| |                                  _____")
        print("   ((_))  || |      (  _                       / /|\ \ ")
        print('   (o o)  || |      ))("),                    | | | | |')
        print("____\_/___||_|_____((__^_))____________________\_\|/_/__")
        print('')
        print(tr.fill('After walking for what appeared an entire week, you are dying of thirst. \nYou see in the distance an oasis. '))
        choice2 = input('\nDo you RUN towards it or IGNORE it? ')

        if choice2.lower() == 'run' :
            print()
            print(tr.fill('That oasis was a hallucination. Sadly, because you ran without a thought you got lost without food and water and died.'))
            print('')
            print("      .-.")
            print("     (o.o)")
            print("      |=|")
            print("     __|__")
            print("   //.=|=.\\")
            print("  // .=|=. \\")
            print("  \\ .=|=. //")
            print("   \\(_=_)//")
            print("    (:| |:)")
            print("     || ||")
            print("     () ()")
            print("     || ||")
            print("     || ||")
            print("    ==' '==")
            print('')
            print("  _______ _    _ ______   ______ _   _ _____      ")
            print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
            print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
            print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
            print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
            print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
            print('')
            print("Don't worry you can find the treasure other time. \n") 

        elif choice2.lower() == 'ignore' :
            print()
            print(tr.fill("That oasis was a hallucination. Aren't you glad you ignored it? Because you kept walking, trying to find the treasure, you found another person. He told you he was looking for the treasure as well, and that the treasure wasn't in the desert."))
            choice3 = input('\nDo you TRUST in this treasure hunter and go back to search the treasure \nin the mountains or IGNORE him, he looks suspicious?  ')

            if choice3.lower() == 'ignore' :
                print()
                print(tr.fill("Because you didn't trust him, you wandered the desert without a thought. When you wanted to go back you coudn't find your way. As you didn't brought food or water, you died."))
                print('')
                print("      .-.")
                print("     (o.o)")
                print("      |=|")
                print("     __|__")
                print("   //.=|=.\\")
                print("  // .=|=. \\")
                print("  \\ .=|=. //")
                print("   \\(_=_)//")
                print("    (:| |:)")
                print("     || ||")
                print("     () ()")
                print("     || ||")
                print("     || ||")
                print("    ==' '==")
                print('')
                print("  _______ _    _ ______   ______ _   _ _____      ")
                print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
                print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
                print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
                print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
                print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
                print('')
                print("Don't worry you can find the treasure other time \n") 
            
            elif choice3.lower() == 'trust' :
                print()
                print(tr.fill("Because you trusted him, you can rule out the desert as a place where the treasure is. Sadly, you've spent your entire day in the desert and have to go home."))
                print('\nNext morning you are ready to explore the mountains')
                    
                print("\n        _    .  ,   .           .")
                print("    *  / \_ *  / \_         *        *   /\'__        *")
                print("      /    \  /    \,             .    _/  /  \  *'.")
                print(" .   /\/\  /\/ :' __ \_  `          _^/  ^/    `--.")
                print("    /    \/  \  _/  \-'\      *    /.' ^_   \_   .'\  *")
                print("  /\  .-   `. \/     \ /==~=-=~=-=-;.  _/ \ -. `_/   \ ")
                print(" /  `-.__ ^   / .-'.--\ =-=~_=-=~=^/  _ `--./ .-'  `- \ ")
                print("/        `.  / /       `.~-^=-=~=^=.-'      '-._ `._   \ \n")
                print('\nThey say a dragon lives in the mountains.')
                choice = input('\nAre you sure you want to explore them (YES/NO)? \nThey say a dragon lives in there. ')

                if choice.lower() == 'no' :
                    print("\nDon't worry a dragon scares most people. \n")
                    print("You decided that you don't need a trasure, it is better to be alive.")
                    print('')
                    print("  _______ _    _ ______   ______ _   _ _____      ")
                    print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
                    print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
                    print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
                    print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
                    print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
                    print('')

                elif choice.lower() == 'yes' :
                    print()
                    print(tr.fill('Good choice! Here in the mountains there should be fewer places to search for the treasure.'))
                    print('\nAfter a couple of hours hiking, you see a crumbling castle.')
                    print("   /\                                                        /\ ")
                    print("  |  |                                                      |  |")
                    print(" /----\                                                    /----\ ")
                    print("[______]                                                  [______]")
                    print(" |    |         _____                        _____         |    |")
                    print(" |[]  |        [     ]                      [     ]        |  []|")
                    print(" |    |       [_______][ ][ ][ ][][ ][ ][ ][_______]       |    |")
                    print(" |    [ ][ ][ ]|     |  ,----------------,  |     |[ ][ ][ ]    |")
                    print(" |             |     |/'    ____..____    '\|     |             |")
                    print("  \  []        |     |    /'    ||    '\    |     |        []  / ")
                    print("   |      []   |     |   |o     ||     o|   |     |  []       |")
                    print("   |           |  _  |   |     _||_     |   |  _  |           |")
                    print("   |   []      | (_) |   |    (_||_)    |   | (_) |       []  |")
                    print("   |           |     |   |     (||)     |   |     |           |")
                    print("   |           |     |   |      ||      |   |     |           |")
                    print(" /''           |     |   |o     ||     o|   |     |           ''\ ")
                    print("[_____________[_______]--'------''------'--[_______]_____________]\n")

                    choice = input("Do you want to EXPLORE or do you keep WALKING? \nMaybe you'll find someplace else where the treasure might be. ")


                    if choice.lower() == 'explore' :
                        print()
                        print(tr.fill('You are the bravest person I know. Once you are inside the castle you see on the mezzanine two different color doors. \n'))
                        choice = input ('Do you want to explore inside the RED door or the BLACK one? ')

                        if choice.lower() == 'red' :
                            print('')
                            print(" __     __         _              __                      _ ")  
                            print(" \ \   / /        ( )            / _|                    | |")  
                            print("  \ \_/ /__  _   _|/__   _____  | |_ ___  _   _ _ __   __| | ") 
                            print("   \   / _ \| | | | \ \ / / _ \ |  _/ _ \| | | | '_ \ / _` |")  
                            print("    | | (_) | |_| |  \ V /  __/ | || (_) | |_| | | | | (_| | ") 
                            print("  _ |_|\___/ \__,_|_  \_/ \___| |_| \___/ \__,_|_| |_|\__,_| ") 
                            print(" | | | |          | |                                     ")    
                            print(" | |_| |__   ___  | |_ _ __ ___  __ _ ___ _   _ _ __ ___  ")    
                            print(" | __| '_ \ / _ \ | __| '__/ _ \/ _` / __| | | | '__/ _ \ ")    
                            print(" | |_| | | |  __/ | |_| | |  __/ (_| \__ \ |_| | | |  __/ ")     
                            print("  \__|_| |_|\___|  \__|_|  \___|\__,_|___/\__,_|_|  \___| ") 
                            print('')
                            print('')
                            print("   _____ ____ _____         _____ ____ _____         _____ ____ _____    ")
                            print("  /    /      \    \       /    /      \    \       /    /      \    \   ")
                            print("/____ /_________\____\   /____ /_________\____\   /____ /_________\____\ ")
                            print("\    \          /    /   \    \          /    /   \    \          /    / ")
                            print("   \  \        /  /         \  \        /  /         \  \        /  /    ")
                            print("      \ \    / /               \ \    / /               \ \    / /       ")
                            print("        \ \/ /                   \ \/ /                   \ \/ /         ")
                            print("          \/                       \/                       \/           ")
                            print('')
                            print('')
                            print("  _______ _    _ ______   ______ _   _ _____      ")
                            print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
                            print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
                            print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
                            print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
                            print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
                            print('')

                        elif choice.lower() == 'black' :
                            print("\n <>=======()") 
                            print("(/\___   /|\\          ()==========<>_")
                            print("      \_/ | \\        //|\   ______/ \)")
                            print("        \_|  \\      // | \_/")
                            print("          \|\/|\_   //  /\/")
                            print("           (oo)\ \_//  /")
                            print("          //_/\_\/ /  |")
                            print("         @@/  |=\  \  |")
                            print("              \_=\_ \ |")
                            print("                \==\ \|\_")
                            print("             __(\===\(  )\ ")
                            print("            (((~) __(_/   |")
                            print("                 (((~) \  /")
                            print("                 ______/ /")
                            print("                 '------'\n")
                            print("\nOh no! You've found a dragon, you must defeat it to survive. ")
                            choice = input('\nWhat weapon have you brought with you, a SWORD or a BOW and arrows? ')
                            if choice.lower() == 'sword' :
                                print("\n        /")
                                print("*//////{<>==================-")
                                print("        \ \n")
                                print('')
                                print('')
                                print(tr.fill("After a good fight you have defeated the dragon. You decided to return home, to claim the title of a knight due to your heroic act of defeating a dragon.\n"))
                                print("       !")
                                print("      .-.")
                                print("    __|=|__")
                                print("   (_/`-`\_)")
                                print("   //\___/\\ ")
                                print("   <>/   \<>")
                                print("    \|_._|/ ")
                                print("     <_I_>")
                                print("      |||")
                                print("     /_|_\ ")
                                print('')
                                print('The treasure can be found other day, enjoy your day of glory.\n')
                                print('')
                                print("  _______ _    _ ______   ______ _   _ _____      ")
                                print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
                                print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
                                print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
                                print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
                                print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
                                print('')
                                            
                            elif choice.lower() == 'bow' :
                                print("\n   (")
                                print("    \ ")
                                print("     )")
                                print("##-------->")
                                print("     )")
                                print("    / ")
                                print("   (\n")
                                print(tr.fill("The arrows you've brought couldn't pierce the dragon's scales. But you made the dragon angry, he breathed fire and killed you."))
                                print('')
                                print("      .-.")
                                print("     (o.o)")
                                print("      |=|")
                                print("     __|__")
                                print("   //.=|=.\\")
                                print("  // .=|=. \\")
                                print("  \\ .=|=. //")
                                print("   \\(_=_)//")
                                print("    (:| |:)")
                                print("     || ||")
                                print("     () ()")
                                print("     || ||")
                                print("     || ||")
                                print("    ==' '==")
                                print('')
                                print("  _______ _    _ ______   ______ _   _ _____      ")
                                print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
                                print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
                                print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
                                print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
                                print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
                                print('')
                                print("Don't worry, you can find the treasure another time.\n") 
                            else :
                                print("\033[91m {}\033[00m" .format('\nSorry, we can only play if you follow the rules. \nYou must choose from the CAPITALIZED words.  \n'))
                        else :
                            print("\033[91m {}\033[00m" .format('\nSorry, we can only play if you follow the rules. \nYou must choose from the CAPITALIZED words.  \n'))

                    elif choice.lower() == 'walking' :
                        print()
                        print(tr.fill("Good choice, a few miles away from the castle you found a cave and a bridge that leads to a forest. "))
                        choice = input('\nDo you want to explore the CAVE or take the BRIDGE to the \nforest you see in the distance? ')

                        if choice.lower() == 'bridge' :
                            print()
                            print(tr.fill('The bridge was really old, as soon as you stepped on it broke and you fell to your death.'))
                            print('')
                            print("      .-.")
                            print("     (o.o)")
                            print("      |=|")
                            print("     __|__")
                            print("   //.=|=.\\")
                            print("  // .=|=. \\")
                            print("  \\ .=|=. //")
                            print("   \\(_=_)//")
                            print("    (:| |:)")
                            print("     || ||")
                            print("     () ()")
                            print("     || ||")
                            print("     || ||")
                            print("    ==' '==")
                            print('')
                            print("  _______ _    _ ______   ______ _   _ _____      ")
                            print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
                            print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
                            print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
                            print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
                            print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
                            print('')
                            print("Don't worry you can find the treasure other time.\n") 
                    

                        elif choice.lower() == 'cave' :
                            print('')
                            print(" __     __         _              __                      _ ")  
                            print(" \ \   / /        ( )            / _|                    | |")  
                            print("  \ \_/ /__  _   _|/__   _____  | |_ ___  _   _ _ __   __| | ") 
                            print("   \   / _ \| | | | \ \ / / _ \ |  _/ _ \| | | | '_ \ / _` |")  
                            print("    | | (_) | |_| |  \ V /  __/ | || (_) | |_| | | | | (_| | ") 
                            print("  _ |_|\___/ \__,_|_  \_/ \___| |_| \___/ \__,_|_| |_|\__,_| ") 
                            print(" | | | |          | |                                     ")    
                            print(" | |_| |__   ___  | |_ _ __ ___  __ _ ___ _   _ _ __ ___  ")    
                            print(" | __| '_ \ / _ \ | __| '__/ _ \/ _` / __| | | | '__/ _ \ ")    
                            print(" | |_| | | |  __/ | |_| | |  __/ (_| \__ \ |_| | | |  __/ ")     
                            print("  \__|_| |_|\___|  \__|_|  \___|\__,_|___/\__,_|_|  \___| ") 
                            print('')
                            print(tr.fill("Oh no! You've also found a dragon guarding it. You must defeat the dragon to win the treasure. As well, if you kill the dragon, you can become a knight. \n"))
                            print(" <>=======()") 
                            print("(/\___   /|\\          ()==========<>_")
                            print("      \_/ | \\        //|\   ______/ \)")
                            print("        \_|  \\      // | \_/")
                            print("          \|\/|\_   //  /\/")
                            print("           (oo)\ \_//  /")
                            print("          //_/\_\/ /  |")
                            print("         @@/  |=\  \  |")
                            print("              \_=\_ \ |")
                            print("                \==\ \|\_")
                            print("             __(\===\(  )\ ")
                            print("            (((~) __(_/   |")
                            print("                 (((~) \  /")
                            print("                 ______/ /")
                            print("                 '------'\n")
                            choice = input('\nWhat weapon will you use, a SWORD or your WORDS? \nMaybe you can reason with it. ')

                            if choice.lower() == 'sword' :
                                print("\n        /")
                                print("*//////{<>==================-")
                                print("        \ \n")                
                                print(tr.fill("This dragon has fought with multiple people and knows to not come close to a sword. He breathed fire and killed you."))
                                print('')
                                print("      .-.")
                                print("     (o.o)")
                                print("      |=|")
                                print("     __|__")
                                print("   //.=|=.\\")
                                print("  // .=|=. \\")
                                print("  \\ .=|=. //")
                                print("   \\(_=_)//")
                                print("    (:| |:)")
                                print("     || ||")
                                print("     () ()")
                                print("     || ||")
                                print("     || ||")
                                print("    ==' '==")
                                print('')
                                print("  _______ _    _ ______   ______ _   _ _____      ")
                                print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
                                print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
                                print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
                                print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
                                print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
                                print('')
    
                                            
                            elif choice.lower() == 'words' :
                                print()
                                print (tr.fill("Good choice! This dragon was lonely so he spreaded the rumor of a treasure only to have someone to talk to."))
                                print()
                                print(tr.fill('After hours of talking, the dragon is your friend and allowed you to take part of his the treasure home.'))
                                print('')
                                print("   _____ ____ _____         _____ ____ _____         _____ ____ _____    ")
                                print("  /    /      \    \       /    /      \    \       /    /      \    \   ")
                                print("/____ /_________\____\   /____ /_________\____\   /____ /_________\____\ ")
                                print("\    \          /    /   \    \          /    /   \    \          /    / ")
                                print("   \  \        /  /         \  \        /  /         \  \        /  /    ")
                                print("      \ \    / /               \ \    / /               \ \    / /       ")
                                print("        \ \/ /                   \ \/ /                   \ \/ /         ")
                                print("          \/                       \/                       \/           ")
                                print('')
                                print('')
                                print("  _______ _    _ ______   ______ _   _ _____      ")
                                print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
                                print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
                                print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
                                print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
                                print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
                                print('')
                            else :
                                print("\033[91m {}\033[00m" .format('\nSorry, we can only play if you follow the rules. \nYou must choose from the CAPITALIZED words.  \n'))
                        else :
                            print("\033[91m {}\033[00m" .format('\nSorry, we can only play if you follow the rules. \nYou must choose from the CAPITALIZED words.  \n'))
                    else :
                        print("\033[91m {}\033[00m" .format('\nSorry, we can only play if you follow the rules. \nYou must choose from the CAPITALIZED words.  \n'))
                else :
                    print("\033[91m {}\033[00m" .format('\nSorry, we can only play if you follow the rules. \nYou must choose from the CAPITALIZED words.  \n'))
            else :
                print("\033[91m {}\033[00m" .format('\nSorry, we can only play if you follow the rules. \nYou must choose from the CAPITALIZED words.  \n'))
        else :
            print("\033[91m {}\033[00m" .format('\nSorry, we can only play if you follow the rules. \nYou must choose from the CAPITALIZED words.  \n'))
           

    elif choice1.lower() == 'mountains' :
        print("\n        _    .  ,   .           .")
        print("    *  / \_ *  / \_         *        *   /\'__        *")
        print("      /    \  /    \,             .    _/  /  \  *'.")
        print(" .   /\/\  /\/ :' __ \_  `          _^/  ^/    `--.")
        print("    /    \/  \  _/  \-'\      *    /.' ^_   \_   .'\  *")
        print("  /\  .-   `. \/     \ /==~=-=~=-=-;.  _/ \ -. `_/   \ ")
        print(" /  `-.__ ^   / .-'.--\ =-=~_=-=~=^/  _ `--./ .-'  `- \ ")
        print("/        `.  / /       `.~-^=-=~=^=.-'      '-._ `._   \ \n")
        print('\nThey say a dragon lives in the mountains.')
        choice = input('\nAre you sure you want to explore them (YES/NO)? \nThey say a dragon lives in there. ')

        if choice.lower() == 'no' :
            print("\nDon't worry you can find the treasure other time. \n")

            print('')
            print("  _______ _    _ ______   ______ _   _ _____      ")
            print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
            print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
            print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
            print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
            print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
            print('')

        elif choice.lower() == 'yes' :
            print()
            print(tr.fill('Good choice! Here in the mountains there should be fewer places to search for the treasure.'))
            print()
            print(tr.fill('After a couple of hours hiking, you see a crumbling castle.'))
            print("   /\                                                        /\ ")
            print("  |  |                                                      |  |")
            print(" /----\                                                    /----\ ")
            print("[______]                                                  [______]")
            print(" |    |         _____                        _____         |    |")
            print(" |[]  |        [     ]                      [     ]        |  []|")
            print(" |    |       [_______][ ][ ][ ][][ ][ ][ ][_______]       |    |")
            print(" |    [ ][ ][ ]|     |  ,----------------,  |     |[ ][ ][ ]    |")
            print(" |             |     |/'    ____..____    '\|     |             |")
            print("  \  []        |     |    /'    ||    '\    |     |        []  / ")
            print("   |      []   |     |   |o     ||     o|   |     |  []       |")
            print("   |           |  _  |   |     _||_     |   |  _  |           |")
            print("   |   []      | (_) |   |    (_||_)    |   | (_) |       []  |")
            print("   |           |     |   |     (||)     |   |     |           |")
            print("   |           |     |   |      ||      |   |     |           |")
            print(" /''           |     |   |o     ||     o|   |     |           ''\ ")
            print("[_____________[_______]--'------''------'--[_______]_____________]\n")

            choice = input("Do you want to EXPLORE or do you keep WALKING? \nMaybe you'll find someplace else where the treasure might be. ")


            if choice.lower() == 'explore' :
                print()
                print(tr.fill('You are the bravest person I know. Once you are inside the castle you see on the mezzanine two different color doors. \n'))
                choice = input ('Do you want to explore inside the RED door or the BLACK one? ')

                if choice.lower() == 'red' :
                    print('')
                    print(" __     __         _              __                      _ ")  
                    print(" \ \   / /        ( )            / _|                    | |")  
                    print("  \ \_/ /__  _   _|/__   _____  | |_ ___  _   _ _ __   __| | ") 
                    print("   \   / _ \| | | | \ \ / / _ \ |  _/ _ \| | | | '_ \ / _` |")  
                    print("    | | (_) | |_| |  \ V /  __/ | || (_) | |_| | | | | (_| | ") 
                    print("  _ |_|\___/ \__,_|_  \_/ \___| |_| \___/ \__,_|_| |_|\__,_| ") 
                    print(" | | | |          | |                                     ")    
                    print(" | |_| |__   ___  | |_ _ __ ___  __ _ ___ _   _ _ __ ___  ")    
                    print(" | __| '_ \ / _ \ | __| '__/ _ \/ _` / __| | | | '__/ _ \ ")    
                    print(" | |_| | | |  __/ | |_| | |  __/ (_| \__ \ |_| | | |  __/ ")     
                    print("  \__|_| |_|\___|  \__|_|  \___|\__,_|___/\__,_|_|  \___| ") 
                    print('')
                    print('')
                    print("   _____ ____ _____         _____ ____ _____         _____ ____ _____    ")
                    print("  /    /      \    \       /    /      \    \       /    /      \    \   ")
                    print("/____ /_________\____\   /____ /_________\____\   /____ /_________\____\ ")
                    print("\    \          /    /   \    \          /    /   \    \          /    / ")
                    print("   \  \        /  /         \  \        /  /         \  \        /  /    ")
                    print("      \ \    / /               \ \    / /               \ \    / /       ")
                    print("        \ \/ /                   \ \/ /                   \ \/ /         ")
                    print("          \/                       \/                       \/           ")
                    print('')
                    print('')
                    print("  _______ _    _ ______   ______ _   _ _____      ")
                    print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
                    print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
                    print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
                    print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
                    print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
                    print('')

                elif choice.lower() == 'black' :
                    print("\n <>=======()") 
                    print("(/\___   /|\\          ()==========<>_")
                    print("      \_/ | \\        //|\   ______/ \)")
                    print("        \_|  \\      // | \_/")
                    print("          \|\/|\_   //  /\/")
                    print("           (oo)\ \_//  /")
                    print("          //_/\_\/ /  |")
                    print("         @@/  |=\  \  |")
                    print("              \_=\_ \ |")
                    print("                \==\ \|\_")
                    print("             __(\===\(  )\ ")
                    print("            (((~) __(_/   |")
                    print("                 (((~) \  /")
                    print("                 ______/ /")
                    print("                 '------'\n")
                    print("\nOh no! You've found a dragon, you must defeat it to survive. ")
                    choice = input('\nWhat weapon have you brought with you, a SWORD or a BOW and arrows? ')
                    if choice.lower() == 'sword' :
                        print("\n        /")
                        print("*//////{<>==================-")
                        print("        \ \n")
                        print('')
                        print('')
                        print(tr.fill("After a good fight you have defeated the dragon. You decided to return home, to claim the title of a knight due to your heroic act of defeating a dragon."))
                        print()
                        print("       !")
                        print("      .-.")
                        print("    __|=|__")
                        print("   (_/`-`\_)")
                        print("   //\___/\\ ")
                        print("   <>/   \<>")
                        print("    \|_._|/ ")
                        print("     <_I_>")
                        print("      |||")
                        print("     /_|_\ ")
                        print('')
                        print('The treasure can be found other day, enjoy your day of glory.\n')
                        print('')
                        print("  _______ _    _ ______   ______ _   _ _____      ")
                        print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
                        print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
                        print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
                        print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
                        print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
                        print('')
                                    
                    elif choice.lower() == 'bow' :
                        print("\n   (")
                        print("    \ ")
                        print("     )")
                        print("##-------->")
                        print("     )")
                        print("    / ")
                        print("   (\n")
                        print(tr.fill("The arrows you've brought couldn't pierce the dragon's scales. But you made the dragon angry, he breathed fire and killed you."))
                        print('')
                        print("      .-.")
                        print("     (o.o)")
                        print("      |=|")
                        print("     __|__")
                        print("   //.=|=.\\")
                        print("  // .=|=. \\")
                        print("  \\ .=|=. //")
                        print("   \\(_=_)//")
                        print("    (:| |:)")
                        print("     || ||")
                        print("     () ()")
                        print("     || ||")
                        print("     || ||")
                        print("    ==' '==")
                        print('')
                        print("  _______ _    _ ______   ______ _   _ _____      ")
                        print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
                        print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
                        print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
                        print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
                        print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
                        print('')
                        print("Don't worry, you can find the treasure another time.\n") 
                    else :
                        print("\033[91m {}\033[00m" .format('\nSorry, we can only play if you follow the rules. \nYou must choose from the CAPITALIZED words.  \n'))
                else:
                    print("\033[91m {}\033[00m" .format('\nSorry, we can only play if you follow the rules. \nYou must choose from the CAPITALIZED words.  \n'))

            elif choice.lower() == 'walking' :
                print()
                print(tr.fill("Good choice, a few miles away from the castle you found a cave and a bridge that leads to a forest. "))
                choice = input('\nDo you want to explore the CAVE or take the BRIDGE? ')

                if choice.lower() == 'bridge' :
                    print()
                    print(tr.fill('The bridge was really old, as soon as you stepped on it broke and you fell to your death.'))
                    print('')
                    print("      .-.")
                    print("     (o.o)")
                    print("      |=|")
                    print("     __|__")
                    print("   //.=|=.\\")
                    print("  // .=|=. \\")
                    print("  \\ .=|=. //")
                    print("   \\(_=_)//")
                    print("    (:| |:)")
                    print("     || ||")
                    print("     () ()")
                    print("     || ||")
                    print("     || ||")
                    print("    ==' '==")
                    print('')
                    print("  _______ _    _ ______   ______ _   _ _____      ")
                    print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
                    print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
                    print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
                    print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
                    print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
                    print('')
                    print("Don't worry you can find the treasure other time.\n") 
            

                elif choice.lower() == 'cave' :
                    print('')
                    print(" __     __         _              __                      _ ")  
                    print(" \ \   / /        ( )            / _|                    | |")  
                    print("  \ \_/ /__  _   _|/__   _____  | |_ ___  _   _ _ __   __| | ") 
                    print("   \   / _ \| | | | \ \ / / _ \ |  _/ _ \| | | | '_ \ / _` |")  
                    print("    | | (_) | |_| |  \ V /  __/ | || (_) | |_| | | | | (_| | ") 
                    print("  _ |_|\___/ \__,_|_  \_/ \___| |_| \___/ \__,_|_| |_|\__,_| ") 
                    print(" | | | |          | |                                     ")    
                    print(" | |_| |__   ___  | |_ _ __ ___  __ _ ___ _   _ _ __ ___  ")    
                    print(" | __| '_ \ / _ \ | __| '__/ _ \/ _` / __| | | | '__/ _ \ ")    
                    print(" | |_| | | |  __/ | |_| | |  __/ (_| \__ \ |_| | | |  __/ ")     
                    print("  \__|_| |_|\___|  \__|_|  \___|\__,_|___/\__,_|_|  \___| ") 
                    print('')
                    print(tr.fill("Oh no! You've also found a dragon guarding it. You must defeat the dragon to win the treasure. As well, if you kill the dragon, you can become a knight. \n"))
                    print()
                    print(" <>=======()") 
                    print("(/\___   /|\\          ()==========<>_")
                    print("      \_/ | \\        //|\   ______/ \)")
                    print("        \_|  \\      // | \_/")
                    print("          \|\/|\_   //  /\/")
                    print("           (oo)\ \_//  /")
                    print("          //_/\_\/ /  |")
                    print("         @@/  |=\  \  |")
                    print("              \_=\_ \ |")
                    print("                \==\ \|\_")
                    print("             __(\===\(  )\ ")
                    print("            (((~) __(_/   |")
                    print("                 (((~) \  /")
                    print("                 ______/ /")
                    print("                 '------'\n")
                    choice = input('\nWhat weapon will you use, a SWORD or your WORDS? \nMaybe you can reason with it. ')

                    if choice.lower() == 'sword' :
                        print("\n        /")
                        print("*//////{<>==================-")
                        print("        \ \n")                
                        print(tr.fill("This dragon has fought with multiple people and knows to not come close to a sword. He breathed fire and killed you."))
                        print('')
                        print("      .-.")
                        print("     (o.o)")
                        print("      |=|")
                        print("     __|__")
                        print("   //.=|=.\\")
                        print("  // .=|=. \\")
                        print("  \\ .=|=. //")
                        print("   \\(_=_)//")
                        print("    (:| |:)")
                        print("     || ||")
                        print("     () ()")
                        print("     || ||")
                        print("     || ||")
                        print("    ==' '==")
                        print('')
                        print("  _______ _    _ ______   ______ _   _ _____      ")
                        print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
                        print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
                        print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
                        print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
                        print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
                        print('')
    
                                            
                    elif choice.lower() == 'words' :
                        print()
                        print (tr.fill("Good choice! This dragon was lonely so he spreaded the rumor of a treasure only to have someone to talk to."))
                        print()
                        print(tr.fill('After hours of talking, the dragon is your friend and allowed you to take part of his the treasure home.'))
                        print('')
                        print("   _____ ____ _____         _____ ____ _____         _____ ____ _____    ")
                        print("  /    /      \    \       /    /      \    \       /    /      \    \   ")
                        print("/____ /_________\____\   /____ /_________\____\   /____ /_________\____\ ")
                        print("\    \          /    /   \    \          /    /   \    \          /    / ")
                        print("   \  \        /  /         \  \        /  /         \  \        /  /    ")
                        print("      \ \    / /               \ \    / /               \ \    / /       ")
                        print("        \ \/ /                   \ \/ /                   \ \/ /         ")
                        print("          \/                       \/                       \/           ")
                        print('')
                        print('')
                        print("  _______ _    _ ______   ______ _   _ _____      ")
                        print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
                        print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
                        print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
                        print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
                        print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
                        print('')
                    else :
                        print("\033[91m {}\033[00m" .format('\nSorry, we can only play if you follow the rules. \nYou must choose from the CAPITALIZED words.  \n'))
                else:
                    print("\033[91m {}\033[00m" .format('\nSorry, we can only play if you follow the rules. \nYou must choose from the CAPITALIZED words.  \n'))
            else :
                print("\033[91m {}\033[00m" .format('\nSorry, we can only play if you follow the rules. \nYou must choose from the CAPITALIZED words.  \n'))
        else :
            print("\033[91m {}\033[00m" .format('\nSorry, we can only play if you follow the rules. \nYou must choose from the CAPITALIZED words.  \n'))
    elif choice1.lower() == 'forest' :
        print("    v .   ._, |_  .,        v .   ._, |_  .,")
        print("   `-._\/  .  \ /    |/_   `-._\/  .  \ /    |/_")
        print("       \\  _\, y | \//       \\  _\, y | \// ")
        print(" _\_.___\\, \\/ -.\|| _\_.___\\, \\/ -.\||")
        print("   `/-,--.`._||  / / ,   `/-,--.`._||  / / ,")
        print("   /'     `-. `./ / |/_.'/'     `-. `./ / |/_.'")
        print("          |    |//               |    |// ")
        print("          |_    /                |_    / ")
        print("          |-   |                 |-   |") 
        print("          |   =|                 |   =|")
        print("          |    |                 |    |")
        print("------- -/ ,  . \---------------/ ,  . \-----") 
        print('')
        print(tr.fill("As you are walking though the forest you hear the rustling of leaves. Someone or something is around there as well."))
        choice = input('Do you keep WALKING or do you go HOME? ')
        if choice.lower() == 'home' :
            print()
            print(tr.fill("Better safe than sorry right?. \nDon't worry you can search for the treasure other time. "))
            print('')
            print("  _______ _    _ ______   ______ _   _ _____      ")
            print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
            print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
            print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
            print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
            print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
            print('')
        elif choice.lower() == 'walking' :
            print('\nThe sounds keep getting closer and closer.')
            choice = input('Are you sure you want to keep walking (YES/NO)? ')
            if choice.lower() == 'no' :
                print("\nThat was a good choice. They say a dragon lives around here.\n")
                print('You decide to search for the treasure other day.')
                print('')
                print("  _______ _    _ ______   ______ _   _ _____      ")
                print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
                print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
                print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
                print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
                print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
                print('')    
            elif choice.lower() == 'yes' :
                print ('Oh no! You have found the source of the sound. Your older brother! \n')
                print('"How could you put yourself in danger. Wait until I tell mother about this." he says. ')
                print('\nWhen your brother, told your mother of your adventure she killed you.')
                print('')
                print("      .-.")
                print("     (o.o)")
                print("      |=|")
                print("     __|__")
                print("   //.=|=.\\")
                print("  // .=|=. \\")
                print("  \\ .=|=. //")
                print("   \\(_=_)//")
                print("    (:| |:)")
                print("     || ||")
                print("     () ()")
                print("     || ||")
                print("     || ||")
                print("    ==' '==")
                print('')
                print(tr.fill('Just kidding, she did not actually killed you but might as well. You are now in charge of cleaning the stables of every house in your village.'))
                print('\n"I will never search foranother treasure" you tell yourself.')
                print('')
                print("  _______ _    _ ______   ______ _   _ _____      ")
                print(" |__   __| |  | |  ____| |  ____| \ | |  __ \     ")
                print("    | |  | |__| | |__    | |__  |  \| | |  | |    ")
                print("    | |  |  __  |  __|   |  __| | . ` | |  | |    ")
                print("    | |  | |  | | |____  | |____| |\  | |__| |   ")
                print("    |_|  |_|  |_|______| |______|_| \_|_____/  ")
                print('')
            else :
                print("\033[91m {}\033[00m" .format('\nSorry, we can only play if you follow the rules. \nYou must choose from the CAPITALIZED words.  \n'))
        else :
            print("\033[91m {}\033[00m" .format('\nSorry, we can only play if you follow the rules. \nYou must choose from the CAPITALIZED words.  \n'))

    else :
        print("\033[91m {}\033[00m" .format('\nSorry, we can only play if you follow the rules. \nYou must choose from the CAPITALIZED words.  \n'))

else :
    print("\033[91m {}\033[00m" .format('\nSorry, we can only play if you follow the rules. \nYou must choose from the CAPITALIZED words.  \n'))       
